name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        scala: [212, 213]
        exclude:
          - os: macos-latest
            scala: 212

    steps:

    - uses: actions/checkout@v1

    - name: coursier cache (Linux)
      uses: actions/cache@v1
      if: runner.OS == 'Linux'
      with:
        path: ~/.cache/coursier
        key: ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }} # -${{ hashFiles('project/**.scala') }} (fails for now)
        restore-keys: |
          ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
          ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-
          ${{ runner.OS }}-coursier-cache-

    - name: coursier cache (macOS)
      uses: actions/cache@v1
      if: runner.OS == 'macOS'
      with:
        path: ~/Library/Caches/Coursier
        key: ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }} # -${{ hashFiles('project/**.scala') }} (fails for now)
        restore-keys: |
          ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
          ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-
          ${{ runner.OS }}-coursier-cache-

    - uses: olafurpg/setup-scala@v5
      with:
        java-version: graalvm@19.2.1

    - name: Install native-image
      run: gu install native-image

    - name: Test
      run: csbt scala${{ matrix.scala }} test

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: coursier cache (Linux)
        uses: actions/cache@v1
        if: runner.OS == 'Linux'
        with:
          path: ~/.cache/coursier
          key: ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }} # -${{ hashFiles('project/**.scala') }} (fails for now)
          restore-keys: |
            ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
            ${{ runner.OS }}-coursier-cache-${{ matrix.scala }}-
            ${{ runner.OS }}-coursier-cache-

      - uses: olafurpg/setup-scala@v5

      - uses: olafurpg/setup-gpg@v2

      - name: Release
        run: (csbt scala212 publishLocal || csbt scala212 publishLocal) && (csbt scala213 publishLocal || csbt scala213 publishLocal) && csbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
